import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { isWarpBeamReplaced, isBobinReplaced } from "./beamReplacementUtils";

function Notifications() {
  const [notifications, setNotifications] = useState([]);
  const [filterTab, setFilterTab] = useState("all"); // 'all' | 'unread'
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadNotifications();

    function handlePlacementChange() {
      loadNotifications();
    }

    window.addEventListener("powerloom_beam_replaced", handlePlacementChange);
    window.addEventListener("powerloom_bobin_replaced", handlePlacementChange);
    return () => {
      window.removeEventListener("powerloom_beam_replaced", handlePlacementChange);
      window.removeEventListener("powerloom_bobin_replaced", handlePlacementChange);
    };
  }, []);

  async function loadNotifications() {
    setLoading(true);

    const { data, error } = await supabase
      .from("notifications")
      .select(`
        *,
        looms (
          id,
          loom_number
        ),
        warps (
          id,
          warp_id
        )
      `)
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Error loading notifications:", error);
      setLoading(false);
      return;
    }

    setNotifications(data || []);
    setLoading(false);
  }

  async function markAsRead(id) {
    const { error } = await supabase
      .from("notifications")
      .update({ is_read: true })
      .eq("id", id);

    if (error) {
      console.error(error);
      return;
    }

    await loadNotifications();
  }

  async function markAllAsRead() {
    const { error } = await supabase
      .from("notifications")
      .update({ is_read: true })
      .eq("is_read", false);

    if (error) {
      console.error(error);
      return;
    }

    await loadNotifications();
  }

  async function deleteNotification(id) {
    const confirmed = window.confirm("Delete this notification?");
    if (!confirmed) return;

    const { error } = await supabase
      .from("notifications")
      .delete()
      .eq("id", id);

    if (error) {
      console.error(error);
      return;
    }

    await loadNotifications();
  }

  if (loading) {
    return (
      <div className="page-container">
        <div className="page-heading">
          <div>
            <div className="page-eyebrow">SYSTEM</div>
            <h2>Notifications</h2>
            <p>Production alerts, 70% capacity thresholds, and warp completions.</p>
          </div>
        </div>
        <div className="page-loading">
          <div className="loading-spinner"></div>
          <p>Loading notifications...</p>
        </div>
      </div>
    );
  }

  // If empty beam is placed, cancel that beam notification alone!
  // If bobin is placed, cancel that bobin notification alone!
  const isNotificationCancelled = (n) => {
    if (n.warp_id && isWarpBeamReplaced(n.warp_id) && !n.title?.toLowerCase().includes("bobin")) {
      return true;
    }
    if (n.bobin_id && isBobinReplaced(n.bobin_id)) {
      return true;
    }
    return false;
  };

  const unreadCount = notifications.filter(
    (n) => !n.is_read && !isNotificationCancelled(n)
  ).length;

  const displayedNotifications = (
    filterTab === "unread"
      ? notifications.filter((n) => !n.is_read)
      : notifications
  ).filter((n) => !isNotificationCancelled(n));

  return (
    <div className="page-container">
      {/* PAGE HEADER */}
      <div className="page-heading">
        <div>
          <span className="page-eyebrow">SYSTEM ALERTS</span>
          <h2>Notifications</h2>
        </div>

        <div className="notification-header-actions">
          <div className="notification-count-card">
            <span>Unread</span>
            <strong>{unreadCount}</strong>
          </div>

          {unreadCount > 0 && (
            <button
              type="button"
              className="secondary-button"
              onClick={markAllAsRead}
            >
              Mark All as Read
            </button>
          )}
        </div>
      </div>

      {/* TABS */}
      <div className="content-card">
        <div className="content-card-header">
          <div>
            <h3>Notification Center</h3>
            <p>Automatic alerts generated by production thresholds.</p>
          </div>

          <div className="header-tab-group">
            <button
              type="button"
              className={`header-tab ${filterTab === "all" ? "active" : ""}`}
              onClick={() => setFilterTab("all")}
            >
              All ({notifications.length})
            </button>
            <button
              type="button"
              className={`header-tab ${filterTab === "unread" ? "active" : ""}`}
              onClick={() => setFilterTab("unread")}
            >
              Unread ({unreadCount})
            </button>
          </div>
        </div>

        {displayedNotifications.length === 0 ? (
          <div className="empty-state">
            <div className="notification-empty-icon">✓</div>
            <h4>No {filterTab} notifications</h4>
            <p>Everything is up to date. New production alerts will trigger automatically.</p>
          </div>
        ) : (
          <div className="notification-list">
            {displayedNotifications.map((notification) => {
              const isUnread = !notification.is_read;
              const is70Alert =
                notification.notification_type === "loom_70" ||
                notification.notification_type === "bobin_70" ||
                notification.title?.includes("70%") ||
                notification.notification_type === "loom_55";
              const isBobinAlert =
                notification.title?.toLowerCase().includes("bobin") ||
                notification.notification_type === "bobin_70";
              const isWarpCompleted = notification.notification_type === "warp_completed";

              return (
                <div
                  key={notification.id}
                  className={`notification-card ${isUnread ? "notification-unread" : "notification-read"}`}
                >
                  <div className="notification-content">
                    <div className="notification-title-row">
                      <div
                        className={`notification-status-dot ${isUnread ? "notification-dot-unread" : "notification-dot-read"}`}
                      />
                      <h3>{notification.title}</h3>
                      {is70Alert && (
                        <span className="badge badge-warning">
                          {isBobinAlert ? "BOBIN 70% ALERT" : "70% CAPACITY ALERT"}
                        </span>
                      )}
                      {isWarpCompleted && (
                        <span className="badge badge-success">WARP COMPLETED</span>
                      )}
                      {isUnread && (
                        <span className="notification-new-badge">New</span>
                      )}
                    </div>

                    <p className="notification-message">{notification.message}</p>

                    {(notification.looms || notification.warps) && (
                      <div className="notification-details">
                        {notification.looms && (
                          <div className="notification-detail">
                            <span>Loom</span>
                            <strong>Loom {notification.looms.loom_number}</strong>
                          </div>
                        )}
                        {notification.warps && (
                          <div className="notification-detail">
                            <span>Warp</span>
                            <strong>{notification.warps.warp_id}</strong>
                          </div>
                        )}
                      </div>
                    )}

                    <div className="notification-time">
                      {new Date(notification.created_at).toLocaleString()}
                    </div>
                  </div>

                  <div className="notification-actions">
                    {isUnread && (
                      <button
                        type="button"
                        className="secondary-button small"
                        onClick={() => markAsRead(notification.id)}
                      >
                        Mark Read
                      </button>
                    )}
                    <button
                      type="button"
                      className="danger-outline-button small"
                      onClick={() => deleteNotification(notification.id)}
                    >
                      Delete
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}

export default Notifications;